### ISSUE TITLE
12 test failures in api.javasoft.sqe.tests.javax.mail

### ISSUE THREAD

**Issue by alwin-joseph** [eclipse-ee4j/javamail-tck#3]
Below tests are failing:
api.javasoft.sqe.tests.javax.mail.Multipart.testlist.html.addBodyPart1_Test 
api.javasoft.sqe.tests.javax.mail.Multipart.testlist.html.addBodyPart2_Test 
api.javasoft.sqe.tests.javax.mail.Provider.testlist.html.getType_Test 
api.javasoft.sqe.tests.javax.mail.Session.testlist.html.getTransport_Test 
api.javasoft.sqe.tests.javax.mail.Transport.testlist.html.autoclose_Test 
api.javasoft.sqe.tests.javax.mail.Transport.testlist.html.close_Test 
api.javasoft.sqe.tests.javax.mail.Transport.testlist.html.connect_Test 
api.javasoft.sqe.tests.javax.mail.Transport.testlist.html.getURLName_Test 
api.javasoft.sqe.tests.javax.mail.Transport.testlist.html.isConnected_Test 
api.javasoft.sqe.tests.javax.mail.Transport.testlist.html.sendMessage_Test 
api.javasoft.sqe.tests.javax.mail.Transport.testlist.html.send_Test 
api.javasoft.sqe.tests.javax.mail.event.TransportEvent.testlist.html.addTransportListener_Test

Test report: https://jenkins.eclipse.org/jakartaee-tck/job/standalonetck-nightly-build-run/127/junit-reports-with-handlebars/test-summary/c01b7780-b43b-4747-b7a3-7ca30743e399.html

The failures seem to be related to the mailserver setup, but not confirmed yet.
All the failures are consistent and they have never passed in eclipse infra.

**Comment by bshannon** [comment]
I suspect that `JAVAMAIL_TRANSPORT_PROTOCOL=smtp` is missing from the javamail.jte file.

**Comment by bshannon** [comment]
I fixed the configuration and this is working now.
